name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:

    name: Test Python ${{ matrix.python_version }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: [3.9]
    env:
      PYTHONDEVMODE: 1
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

   - name: Update pip
      run: |
        python -m pip install -U pip

   - name: Install prod deps
      run: |
        python -m pip install -r requirements.txt

   - name: Install dev deps
      run: |
        python -m pip install -r dev-requirements.txt

    - name: Lint with flake8
      run: |
        python -m flake8

    - name: Lint with mypy
      run: |
        python -m mypy

    - name: Check format with Black
      run: |
        python -m black --check .
